version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=2525
      - POSTGRES_USER=root
      - POSTGRES_DB=onlyfoods

    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
